### ISSUE TITLE
Policy for supporting and testing against various OpenStack version?

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [cloudfoundry/bosh-openstack-cpi-release#103]
Hi folks,

I see in the README this project CI's against Liberty, Mitaka, and Newton.  According to https://releases.openstack.org, Liberty and Mitaka are past EOL and Legacy Support (Phase III), and Ocata and Pike have been released this year.

1. How are the versions of OpenStack that get tested decided today?
2. Do the versions of OpenStack supported by this CPI correspond 1-to-1 with the versions that are CI'd against, or is there any notion of declaring support for other versions and just not testing against all supported versions (because there may be other factors making it difficult to test against so many versions)?
3. Going forward, would there be any thought towards having a CI policy expressed in terms of the upstream https://releases.openstack.org policy, e.g. CI'ing the most recent EOL version plus all but the most recent active (non-EOL) versions?
4. Likewise, what about a support policy also expressed in terms of upstream supported versions.

I'm sure in reality there are complexities related to how you're getting your OpenStack test environments (e.g. from some vendor), but I wonder if there could be a more generally predictable or vendor-agnostic policy that's not too far outside what's possible to actually test against.

**Comment by voelzmo** [comment]
Hi @Amit-PivotalLabs,

thanks for bringing this up! Let's talk first about the theory behind what we're doing and then we get to the practicalities.

**theory**
> How are the versions of OpenStack that get tested decided today?

That's currently decided very locally in our team. We don't have an official process for this.

> Do the versions of OpenStack supported by this CPI correspond 1-to-1 with the versions that are CI'd against, or is there any notion of declaring support for other versions and just not testing against all supported versions (because there may be other factors making it difficult to test against so many versions)?

We only list 'supported versions' when we actively CI against them.

> Going forward, would there be any thought towards having a CI policy expressed in terms of the upstream https://releases.openstack.org policy, e.g. CI'ing the most recent EOL version plus all but the most recent active (non-EOL) versions?

That was our goal when we started: Supporting whatever OpenStack lists as 'officially supported' releases (i.e. the last 3 ones) plus potentially the newest EOL version.

> Likewise, what about a support policy also expressed in terms of upstream supported versions.

I'm not sure how you distinguish between 'support policy' and 'CI policy' from the previous question. Could you elaborate a bit more on the difference?

**practice**
* we're unable to setup and maintain stable OpenStack environments from open-source upstream ourselves, therefore we rely on a vendor to do this for us
* OpenStack is released twice a year, most OpenStack vendors, however, only release a product once per year. We do have an agreement, though, to also get the 'intermediary' releases of OpenStack being setup for us
* the vendors' releases lag behind the official release dates by ~3-4 months. This means: while OpenStack pike was released in October 2017, we don't expect a product based on Pike before January 2018

Currently, the situation is especially bad, given that we don't even have an Ocata based test setup running. I understand that for everyone setting up a DevStack to test BOSH against the most recent OpenStack versions it seems weird, that we only test against versions which are EOL for quite some time.

> I wonder if there could be a more generally predictable or vendor-agnostic policy that's not too far outside what's possible to actually test against

We're open for suggestions to improve the situation. Recently, I had a look at vendors providing a publicly available OpenStack, but didn't find a good solution. Do you have anything specific in mind?

**Comment by Amit-PivotalLabs** [comment]
Thanks @voelzmo !

> I'm not sure how you distinguish between 'support policy' and 'CI policy' from the previous question. Could you elaborate a bit more on the difference?

For example, imagine that due to practical considerations you are only able to CI against M and N, but you nonetheless want to signal to users that you're sufficiently confident they can use the CPI against L and O as well.  In that case, you could say you CI against M and N, and support L-O.

A general policy might look like: "we CI against all but the latest active release plus the latest EOL release (so today that would equal M-O) and we support additionally the latest active release plus the next-to-latest EOL release (so today that would equal L-P)."

Not saying that's a good or bad policy, just an example of what a CI policy and support policy could look like.

Here "support" of course just means what it typically means for OSS projects, "we think you'll be successful using it and can help answer questions if you have any," not "you can call us in the middle of the night."  I think vendors would like to say, "we will commercially support whatever the OSS CPI project claims to support."  This gives vendors a more predictable message, so that customers don't have to ask the question every time: "now Queens is out, does <vendor> support BOSH on Queens"?

There are lots of moving pieces:

* OpenStack support policy for releases
* OpenStack vendor support policy for their distributions
* what CPI team CIs/supports
* BOSH vendor support policies

I'm trying to think about which of these policies can be turned into predictable functions of the upstream policy.  In an ideal world, your vendor sticks to your aforementioned agreement with them, allowing the CPI team to CI against a predictable set of OpenStack releases.  Ideally the CPI team also has a support policy that is a predictable function of that (maybe CI'd versions == supported versions, maybe supported versions include 1 extra ahead and/or behind the set of CI'd versions, etc.).  Then BOSH vendors can have some some support policy that is a function of the CPI policy.  And ultimately BOSH customers can more easily reason about their future plans around OpenStack.

> we're unable to setup and maintain stable OpenStack environments from open-source upstream ourselves, therefore we rely on a vendor to do this for us

I can empathize with that pain!

> We're open for suggestions to improve the situation. Recently, I had a look at vendors providing a publicly available OpenStack, but didn't find a good solution. Do you have anything specific in mind?

With respect to OpenStack vendors, no, I think this is an industry-wide challenge.  It's definitely understandable.  Just wanted to have a conversation and understand your team's thinking on this general question of how can customers of BOSH-on-OpenStack reason about their future OpenStack plans as the upstream OpenStack project continues to ship and EOL releases?

**Comment by voelzmo** [comment]
Hey @Amit-PivotalLabs 

Sorry for not following up on this more timely. 

I do agree with many of the things you said. We should really get back on track with the original plan to CI and officially support all OpenStack releases that are non-EOL'ed. We should also communicate that this is our policy and act predictively on it. Ideally, we'd also do additional tests with the currently developed version once it comes closer to being released, so we could ensure it works from day 1 of a new release.

In the past, I've wondered, if the people asking about "does the CPI work on OpenStack X?" shortly after it being released are actually using a hand-rolled open-source version of OpenStack, or if this is more of an academic exercise. In my experience, vendors take their time releasing new versions and skip one release per year. Additionally, many people seem to struggle with updating their OpenStack installations, so I don't see many companies updating their stack twice a year.

**Comment by Amit-PivotalLabs** [comment]
> Sorry for not following up on this more timely.

No sweat :)

> We should really get back on track with the original plan to CI and officially support all OpenStack releases that are non-EOL'ed. We should also communicate that this is our policy and act predictively on it. Ideally, we'd also do additional tests with the currently developed version once it comes closer to being released, so we could ensure it works from day 1 of a new release.

That would be hot!

> In the past, I've wondered, if the people asking about "does the CPI work on OpenStack X?" shortly after it being released are actually using a hand-rolled open-source version of OpenStack, or if this is more of an academic exercise.

Maybe "academic" isn't the right characterization, but it's more about planning.  Some organizations may start planning an upgrade to a new Openstack version many months in advance of doing it, and they need to see if all their ducks will be in a row when that time comes, so they will want to know whether BOSH will be ready at that point in time.

> In my experience, vendors take their time releasing new versions and skip one release per year.

I tend to see Cloud Foundry adopted by very large enterprises, and these large enterprises often have special support from their Openstack vendors.  Very often this takes the form of the vendor supporting a version of Openstack that has gone EOL from the OSS perspective.  I can imagine this also taking the form of a vendor providing support for a very new version of Openstack to a large enterprise account that they wouldn't make generally available right away.

**Comment by Amit-PivotalLabs** [comment]
Also, a data point with regards to vendor support timelines vis a vis OSS timelines, it looks like RedHat makes their versions GA about 3 months after OpenStack org's official release date, and ends maintenance support about 3 months after OpenStack's EOL date.  Compare [OpenStack Releases](https://releases.openstack.org) with the Life Cycle Dates section of [Red Hat OpenStack Platform Life Cycle](https://access.redhat.com/support/policy/updates/openstack/platform)

**Comment by voelzmo** [comment]
This would be very helpful, thanks for reaching out @dims. Let's continue to discuss some details in the cf slack #openstack channel!

**Comment by voelzmo** [comment]
Fixed with https://github.com/cloudfoundry/bosh-openstack-cpi-release/commit/d292dddaaeef55701abf04177edab7b807e53721

Official support policy is now at https://github.com/cloudfoundry/bosh-openstack-cpi-release#supported-openstack-versions

Let me know if this policy doesn't work for you, or if we should word it differently to help you in discussions with your customers.

Thanks @Amit-PivotalLabs for bringing this up and all the OpenLab people for helping us setting this up!

**Comment by Amit-PivotalLabs** [comment]
Thanks!
