### ISSUE TITLE
disk resize miss linux fs resize

### ISSUE THREAD

**Issue by poblin-orange** [cloudfoundry/bosh-openstack-cpi-release#161]
When using openstack resize disk feature , the persistent disk is resized @ iaas level. However, theres a missing step as operators have to resize the fs to take benefit of the full iaas disk capacity

**Comment by poblin-orange** [comment]
Issue still present. Blocking with recent stemcells. Suggest deprecating removing this property as its unsafe

**Comment by bgandon** [comment]
Hi Pierre, you may be happy to hear that I've recently submitted all the necessary changes to the BOSH Agent and BOSH Director for IaaS-native disk _growing_ to properly work.
We now need all that to be reviewed and merged. See cloudfoundry/bosh-agent#244 for updates.
