### ISSUE TITLE
Network Lifecycle Management

### ISSUE THREAD

**Issue by frodenas** [cloudfoundry/bosh-openstack-cpi-release#162]
BOSH [v268.0.1](https://github.com/cloudfoundry/bosh/releases/tag/v268.0.1) introduces beta functionality of [network lifecycle management](https://docs.google.com/document/d/1akr17Iep99fCYNqZQv9uoxar7qF04U40O6cYoAsg3lA/edit). Can we add support for this at the OpenStack  CPI?

**Comment by voelzmo** [comment]
Thanks for the heads-up and checking in on the networking support for OpenStack, Ferdy! We're currently finishing up the last pieces for a new CPI release and will look at networking support for the next one.

**Comment by frodenas** [comment]
Awesome, thanks @voelzmo!
