### ISSUE TITLE
Missing config parameter for different domains

### ISSUE THREAD

**Issue by foexle** [cloudfoundry/bosh-openstack-cpi-release#211]
after some debugging i figured out it's not possible to configure different domain names/ids for user and project. This is necessary in enterprises with multiple IAM backend systems.

**execute**
`bosh create-env bosh-deployment/bosh.yml --state=bosh-state.json --vars-store=director-creds.yml --vars-file=../bosh_vars.yaml -o bosh-deployment/openstack/cpi.yml -o bosh-deployment/external-ip-with-registry-not-recommended.yml --var-file=private_key=bosh.pem`

**result**
`  CPI 'create_stemcell' method responded with error: CmdError{"type":"Bosh::Clouds::CloudError","message":"Unable to connect to the OpenStack Image Service API: Expected([200, 201]) \u003c=\u003e Actual(401 Unauthorized)\nexcon.error.response\n  :body          =\u003e \"{\\\"error\\\": {\\\"message\\\": \\\"The request you have made requires authentication.\\\", \\\"code\\\": 401, \\\"title\\\": \\\"Unauthorized\\\"}}\"\n  :cookies       =\u003e [\n  ]\n  :headers       =\u003e {\n    \"Connection\"             =\u003e \"keep-alive\"\n    \"Content-Length\"         =\u003e \"114\"\n    \"Content-Type\"           =\u003e \"application/json\"\n    \"Date\"                   =\u003e \"Wed, 24 Jul 2019 10:20:36 GMT\"\n    \"Server\"                 =\u003e \"nginx\"\n    \"Vary\"                   =\u003e \"X-Auth-Token\"\n    \"WWW-Authenticate\"       =\u003e \"Keystone uri=\\\"https://example.net:5000\\\"\"\n    \"X-Content-Type-Options\" =\u003e \"nosniff\"\n    \"X-Distribution\"         =\u003e \"Ubuntu\"\n    \"X-Frame-Options\"        =\u003e \"sameorigin\"\n    \"x-openstack-request-id\" =\u003e \"req-9dc5731c-d259-4073-a643-d4ff81dd039f\"\n  }\n  :host          =\u003e \"example.net\"\n  :local_address =\u003e \"10.150.10.2\"\n  :local_port    =\u003e 54018\n  :path          =\u003e \"/v3/auth/tokens\"\n  :port          =\u003e 5000\n  :reason_phrase =\u003e \"Unauthorized\"\n  :remote_ip     =\u003e \"xxxxx\"\n  :status        =\u003e 401\n  :status_line   =\u003e \"HTTP/1.1 401 Unauthorized\\r\\n\"\n. Check task debug log for details.","ok_to_retry":false}
`
**the request**
`excon.request POST https://example:5000/v3/auth/tokens params: {"chunk_size":1048576,"connect_timeout":60,"debug_request":false,"debug_response":tr
ue,"idempotent":false,"instrumentor_name":"excon","mock":false,"nonblock":true,"omit_default_port":false,"persistent":false,"read_timeout":60,"retry_errors":["Excon::Error::Timeout","Excon::Error::Socket","Excon:
:Error::HTTPStatus"],"retry_limit":4,"ssl_verify_peer":true,"ssl_uri_schemes":["https"],"stubs":"global","tcp_nodelay":false,"thread_safe_sockets":true,"versions":"excon/0.64.0 (x86_64-linux) ruby/2.4.6","write_t
imeout":60,"host":"example.net","query":null,"expects":[200,201],"retries_remaining":4} headers: {"User-Agent":"fog-core/2.1.2","Content-Type":"application/json","Host":"example.net:5000"} b
ody: {"auth":{"identity":{"methods":["password"],"password":{"user":{"name":"xxx","domain":{"name":"ldap"},"password":"<redacted>"}}},"scope":{"project":{"name":"test1","domain":{"name":"ldap"}}}}}`

**the bosh vars file:**
> director_name: bosh-1
> internal_cidr: 10.0.1.0/24
> internal_gw: 10.0.1.1
> internal_ip: 10.0.1.10
> external_ip: xxxxx
> auth_url: https://example.com:5000/v3
> az: nova
> default_key_name: boshcf-test-
> default_security_groups: [boshcf-test-]
> net_id: bf6b85a1-39db-4582-b0d1-f4291dddb9cf
> openstack_domain: ldap
> openstack_username: xxxx
> openstack_password: xxxx
> openstack_project: test1
> region: RegionOne
> router_id: 3569ed5d-f0c2-4caf-b9df-ffe2e0a154f8

**expected request**
`[..] password":{"user":{"name":"xxx","domain":{"name":"ldap"},"password":"<redacted>"}}},"scope":{"project":{"name":"test1","domain":{"name":"default"}}}}}`
and not
`[..] password":{"user":{"name":"xxx","domain":{"name":"ldap"},"password":"<redacted>"}}},"scope":{"project":{"name":"test1","domain":{"name":"ldap"}}}}}`

currently the bosh openstack CPI provide only one domain parameter for project and user but it should be separated.

**suggestion**
delete: 

> openstack_domain

add: 
> openstack_user_domain
> openstack_project_domain

**Comment by meowthsli** [comment]
Also it looks like Fog Openstack gem, which CPI release relies on, has a bug: it is not possible to specify `openstack_project_domain_name`, used later in code, because of `recognizes` guards, which does not contain :openstack_project_domain_name key, but :openstack_project_domain only

**Comment by andinod** [comment]
Hi,
is there any news regarding this issue?
