### ISSUE TITLE
Support encrypted volumes

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/bosh-openstack-cpi-release#224]
As a bosh operator, in order to protect data stored in openstack volumes in case of openstack disk being stolen by an attacker, I need the bosh openstack CPI to instruct openstack to encrypt ephemeral and persistent disks. 

See related openstack documentation at https://docs.openstack.org/security-guide/tenant-data/data-encryption.html

Some other CPIs support such feature by leveraging Iaas encryption capabilities:
* See [bosh.io/docs related google search](https://www.google.fr/search?safe=active&sxsrf=ACYBGNRUvA63PeeHY8_Jl9I-X53pPTCF5Q%3A1572256753897&ei=8bu2XYq1NuTRgweCzJ-wCw&q=site%3Abosh.io%2Fdocs+encrypt&oq=site%3Abosh.io%2Fdocs+encrypt&gs_l=psy-ab.3...17935.18520..18622...0.0..0.64.304.5......0....1..gws-wiz.8pyI0KupVow&ved=0ahUKEwjK8b7q2L7lAhXk6OAKHQLmB7YQ4dUDCAo&uact=5)
* See https://docs.pivotal.io/platform/2-7/security/pcf-infrastructure/disk-encrypt.html

**Comment by voelzmo** [comment]
Hey @gberche-orange, thanks for the issue!

It's true that how to encrypt your volumes in an OpenStack installation using BOSH isn't properly documented. Note that we didn't have means to test this, as necessary projects (Barbican) isn't installed in our distribution.

Here's the theory for persistent disks:
* Create a volume type which supports encryption https://docs.openstack.org/cinder/train/configuration/block-storage/volume-encryption.html#create-an-encrypted-volume-type
* Put that volume type in your cloud-config or directly into the CPI's [`default_volume_type`](https://bosh.io/jobs/openstack_cpi?source=github.com/cloudfoundry/bosh-openstack-cpi-release&version=43#p%3dopenstack.default_volume_type)
* Your deployment should use encrypted persistent volumes
* Note that the API for volume creation on OpenStack doesn't have any property for encryption. All special properties have been handed down to volume types, which is a ridiculously generic bag-of-things: https://docs.openstack.org/api-ref/block-storage/v3/?expanded=create-a-volume-detail,create-a-volume-type-detail#create-a-volume-type

The documentation you're linking for ephemeral disks refers to pure nova configuration, so my assumption would be that this is out of the reach for the CPI and just depends on how you configure nova.

Apart from documenting these constraints and links to documentation, do you think there's more work to be done in the CPI? Have you already tried any of this?

**Comment by gberche-orange** [comment]
thanks @voelzmo for your prompt and detailed response !

Vsphere CPI documents independently encryption status for each dis type at https://bosh.io/docs/vsphere/#encryption

Disk Type | Encryption
-- | --
Root Disk | Supported
Ephemeral Disk | Supported
Persistent Disk | Supported

Would the following description be accurate for openstack ? Could `boot from image` mode also benefit from encryption, if so how ? 

Disk Type | Encryption
-- | --
Root Disk | Supported through [boot_from_volume](https://bosh.io/docs/openstack-cpi/#resource-pools) and  `default_volume_type` to select en encrypted disk type as root disk. 
Ephemeral Disk | Supported through tenant-wide openstack nova configuration of [ephemeral disk encryption](https://docs.openstack.org/security-guide/tenant-data/data-encryption.html#ephemeral-disk-encryption)
Persistent Disk | Supported in openstack through CPI's [default_volume_type](https://bosh.io/jobs/openstack_cpi?source=github.com/cloudfoundry/bosh-openstack-cpi-release&version=43#p%3dopenstack.default_volume_type) or disk `type` in [cloud properties](https://bosh.io/docs/openstack-cpi/#disk-pools)

> Apart from documenting these constraints and links to documentation, do you think there's more work to be done in the CPI? Have you already tried any of this?

That's great news. We haven't tested it yet. We might give it a try in our openstack installation (based on Huawei cloud), and contribute the associated documentation in a PR. Thanks again!

**Comment by gberche-orange** [comment]
@voelzmo further checking our Huaweicloud-based openstack installation, it seems that the selection of encryption settings is performed using cinder create disk endpoint through the metadata field and not the volume type field. See https://support.huaweicloud.com/en-us/api-evs/en-us_topic_0102534367.html with extracts reproduced below for convenience.

>    Parameter | Type | Mandatory | Description
>    -- | -- | -- | --
>    volume_type | String | No | Specifies the disk type.                      Currently, the value can be            SSD,            SAS, or            SATA.                       SSD: specifies the ultra-high I/O disk type.            SAS: specifies the high I/O disk type.            SATA: specifies the common I/O disk type.                       If the specified disk type is not available in the AZ, the disk will fail to create.                       NOTE:                                     If the disk is created from a snapshot, the volume_type field must be the same as that of the snapshot's source disk.             For details about disk types, see Disk Types and Disk Performance.
>    
>    Parameters in the metadata field: 
>    
>    Parameter | Type | Mandatory | Description
>    -- | -- | -- | --
>    __system__encrypted | String | No | Specifies the parameter that describes the encryption function in metadata. The value can be 0 (encryption function disabled) or 1 (encryption function enabled). If this parameter does not exist, the disk will not be encrypted by default.
>    __system__cmkid | String | No | Specifies the parameter that describes the encryption CMK ID in metadata. This parameter is used together with __system__encrypted for encryption. The length of cmkid is fixed at 36 bytes.                       NOTE:                        For details about how to obtain the CMK ID, see Querying the List of CMKs.
>    

It seems that the CPI assigns some metadata by default to volumes (as documented into https://github.com/cloudfoundry/docs-bosh/blob/b9192c738dc2e812bcad09d6ca159821fb4eb7f7/content/cpi-api-v1-method/set-disk-metadata.md and illustrated by https://github.com/cloudfoundry/bosh-openstack-cpi-release/blob/7f068c75e1006d70d293c37fdec11610bd960d71/src/bosh_openstack_cpi/spec/integration/volume_spec.rb#L16-L26 ) which are assigned by the bosh-director, according to CPI tests at https://github.com/cloudfoundry/bosh/blob/e44e19d2667c0fc25681ce2b8e472c0bbb81833b/src/spec/integration/cpi_spec.rb#L314-L325 

Is there a way for openstack CPI users or bosh deployment operators to inject specific disk metadata ?

**Comment by gberche-orange** [comment]
@bosh-admin-bot please reopen this issue open as I believe it is still relevant
