### ISSUE TITLE
neutron lbaas is deprecated

### ISSUE THREAD

**Issue by dohq** [cloudfoundry/bosh-openstack-cpi-release#233]
https://wiki.openstack.org/wiki/Neutron/LBaaS/Deprecation

neutron lbaas seems to have been removed from the current version (Ussuri).
Nowadays, octavia is recommended.
Is there any plan to support this?
I was curious because I was trying to install BOSH with ussuri using octavia.

**Comment by mephmanx** [comment]
> https://wiki.openstack.org/wiki/Neutron/LBaaS/Deprecation
> 
> neutron lbaas seems to have been removed from the current version (Ussuri).
> Nowadays, octavia is recommended.
> Is there any plan to support this?
> I was curious because I was trying to install BOSH with ussuri using octavia.

I am trying to install cloudfoundry on a Wallaby cloud and having issues with LBaaS as well.

**Comment by flyersa** [comment]
this really needs to get addressed. You cannot deploy cloudfoundry anymore on most recent openstack versions with lbaas v2 deprecated.
