### ISSUE TITLE
Cinder V2 no longer supported - cannot deploy bosh 

### ISSUE THREAD

**Issue by flyersa** [cloudfoundry/bosh-openstack-cpi-release#247]
I see issues when trying to deploy bosh with openstack from latest checkout:

`Deploying:
  Creating instance 'bosh/0':
    Updating instance disks:
      Updating disks:
        Deploying disk:
          Creating disk with size 65536, cloudProperties property.Map{}, instanceID b8ddb77e-ccd7-46f7-b674-26eb36fba150:
            CPI 'create_disk' method responded with error: CmdError{"type":"Unknown","message":"No endpoint match","ok_to_retry":false}

Exit code 1
`

I guess this is because it wants to use cinderv2. Cinder v2 is deprecated since pike already and no longer available by default on wallaybe and xena.  How can this be fixed?

**Comment by flyersa** [comment]
with 47pre i managed to get it done but the agent does not seem to initalize on the director vm. Also why is the director vm grub locked down with user/pass? It does not even accept the bosh.pem key to ssh into it for further debugging.

`/opt/bosh-1# bosh create-env bosh-deployment/bosh.yml     --state=bosh-state.json     --vars-store=director-creds.yml     --vars-file=vars.yml     -o bosh-deployment/openstack/cpi.yml     -o bosh-deployment/external-ip-with-registry-not-recommended.yml     --var-file=private_key=bosh.pem
Deployment manifest: '/opt/bosh-1/bosh-deployment/bosh.yml'
Deployment state: 'bosh-state.json'

Started validating
  Downloading release 'bosh'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh'... Finished (00:00:00)
  Downloading release 'bpm'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bpm'... Finished (00:00:01)
  Downloading release 'bosh-openstack-cpi'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh-openstack-cpi'... Finished (00:00:00)
  Validating cpi release... Finished (00:00:00)
  Validating deployment manifest... Finished (00:00:00)
  Downloading stemcell... Skipped [Found in local cache] (00:00:00)
  Validating stemcell... Finished (00:00:03)
Finished validating (00:00:05)

Started installing CPI
  Compiling package 'ruby-3.1.0-r0.81.0/9cf1a9582c595fd03eb9c73cd3c4b2d10de10c139f99ab0b9d1a71e5d2b91378'... Finished (00:00:00)
  Compiling package 'bosh_openstack_cpi/2252c3fe19699092e30b13e7899b72480cccb64586364be8828f5bd1ee63d23c'... Finished (00:00:00)
  Installing packages... Finished (00:00:00)
  Rendering job templates... Finished (00:00:00)
  Installing job 'openstack_cpi'... Finished (00:00:00)
Finished installing CPI (00:00:01)

Uploading stemcell 'bosh-openstack-kvm-ubuntu-bionic-go_agent/1.79'... Skipped [Stemcell already uploaded] (00:00:00)

Started deploying
  Deleting VM '50793c40-5cc8-4a35-9311-c7aca21bd657'... Finished (00:00:03)
  Creating VM for instance 'bosh/0' from stemcell 'bbcbc711-937d-426a-ad4d-2fa4c7f990cb'... Finished (00:00:31)
  Waiting for the agent on VM '1fde583b-4e11-4c10-96e2-67eb372c9e40' to be ready... Failed (00:09:59)
Failed deploying (00:10:38)

Cleaning up rendered CPI jobs... Finished (00:00:00)

Deploying:
  Creating instance 'bosh/0':
    Waiting until instance is ready:
      Post "https://mbus:<redacted>@10.19.77.164:6868/agent": dial tcp 10.19.77.164:6868: connect: connection refused

Exit code 1
#`

**Comment by beyhan** [comment]
Regarding the ssh access have you configured `authorized_keys` as described in https://bosh.io/docs/manifest-v2/?

**Comment by flyersa** [comment]
not that i know of. I followed https://bosh.io/docs/openstack-cpi/  in Usage. It has a bosh key in openstack and the keyname is specified in default_keyname with its name.

`- path: /instance_groups/name=bosh/properties/openstack?
  type: replace
  value:
    api_key: ((openstack_password))
    auth_url: ((auth_url))
    default_key_name: ((default_key_name))
`
so it should use default_key_name from vars.yml or not ?

`cat vars.yml
---
director_name: bosh-1
internal_cidr: 10.0.1.0/24
internal_gw: 10.0.1.1
internal_ip: 10.0.1.10
auth_url: xxxxx
az: nova
default_key_name: bosh
default_security_groups: [bosh]
net_id: 9eb86c13-0689-434a-ad81-b17734cfc268
openstack_domain: Default
openstack_username: xxx
openstack_password: xxx
openstack_project: cloudfoundry
region: RegionOne
external_ip: xxxx
`

**Comment by flyersa** [comment]
hmm i tried the wrong username. I can login as user vcap to the vm with the specified private key, but cannot sudo etc. How can i debug the agent? obviously its not running, there is no agent port open and i cannot see a process

**Comment by yaguangtang** [comment]
please take look at this to temp fix this cinder v2 issue https://github.com/cloudfoundry/bosh-openstack-cpi-release/pull/246#issuecomment-1077461121

**Comment by flyersa** [comment]
Hello @yaguangtang i already use v47pre and while the problem with cinder is fixed, the agent is not contacting the controller. logging in to the stemcell after creation of the vm i do not even see a process running related to the agent and no port listenning. So the deployment never finishes as it waits forever for the agent which is not run.

**Comment by yaguangtang** [comment]
@flyersa please take a look at this https://github.com/fog/fog-openstack/pull/518#issuecomment-1081237963, I use the same v47pre version with openstack wallaby, all seem to works.

**Comment by ares** [comment]
Hi, could you please confirm whether this is 1.0.0-pre regression?

**Comment by flyersa** [comment]
Well i also tested the newer stemcell versions for the bionic agent. Stil nothing.

`root@osc191d001:/opt/bosh-1# bosh create-env bosh-deployment/bosh.yml     --state=bosh-state.json     --vars-store=director-creds.yml     --vars-file=vars.yml     -o bosh-deployment/openstack/cpi.yml     -o bosh-deployment/external-ip-with-registry-not-recommended.yml     --var-file=private_key=bosh.pem
Deployment manifest: '/opt/bosh-1/bosh-deployment/bosh.yml'
Deployment state: 'bosh-state.json'

Started validating
  Downloading release 'bosh'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh'... Finished (00:00:00)
  Downloading release 'bpm'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bpm'... Finished (00:00:01)
  Downloading release 'bosh-openstack-cpi'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh-openstack-cpi'... Finished (00:00:00)
  Validating cpi release... Finished (00:00:00)
  Validating deployment manifest... Finished (00:00:00)
  Downloading stemcell... Finished (00:00:11)
  Validating stemcell... Finished (00:00:03)
Finished validating (00:00:16)

Started installing CPI
  Compiling package 'ruby-3.1.0-r0.81.0/9cf1a9582c595fd03eb9c73cd3c4b2d10de10c139f99ab0b9d1a71e5d2b91378'... Finished (00:00:00)
  Compiling package 'bosh_openstack_cpi/2252c3fe19699092e30b13e7899b72480cccb64586364be8828f5bd1ee63d23c'... Finished (00:00:00)
  Installing packages... Finished (00:00:00)
  Rendering job templates... Finished (00:00:00)
  Installing job 'openstack_cpi'... Finished (00:00:00)
Finished installing CPI (00:00:01)

Uploading stemcell 'bosh-openstack-kvm-ubuntu-bionic-go_agent/1.88'... Finished (00:00:17)

Started deploying
  Deleting VM '61f2d1b5-3164-4bea-84e8-192b66245f43'... Finished (00:00:03)
  Creating VM for instance 'bosh/0' from stemcell 'bddedef0-958c-4720-a43d-2a773bf7e90d'... Finished (00:00:51)
  Waiting for the agent on VM 'c3b98402-d3e8-4b6b-ab4b-f551cb8a4402' to be ready... Failed (00:09:59)
Failed deploying (00:10:59)

Cleaning up rendered CPI jobs... Finished (00:00:00)

Deploying:
  Creating instance 'bosh/0':
    Waiting until instance is ready:
      Post "https://mbus:<redacted>@10.19.77.164:6868/agent": dial tcp 10.19.77.164:6868: connect: connection refused

Exit code 1
`

really not sure how to proceed here. Guess the documentation also needs some update

**Comment by beyhan** [comment]
@flyersa do you see anything in the agent logs under `/var/vcap/bosh/log/current`? More details about the different locations are available here https://bosh.io/docs/vm-config/#agent

**Comment by beyhan** [comment]
you should be able to attach the ephemeral disk to another VM where you have admin privileges and look into the logs from there.

**Comment by flyersa** [comment]
ok looks like something is wrong with the dns, i mounted the disk image with rbd map and see this in last in the agent logs:

```
2022-06-24_08:58:15.56389 ********************
2022-06-24_08:58:15.56389 # Generated by bosh-agent
2022-06-24_08:58:15.56390 nameserver 8.8.8.8
2022-06-24_08:58:15.56391
2022-06-24_08:58:15.56391 ********************
2022-06-24_08:58:15.56407 [File System] 2022/06/24 08:58:15 DEBUG - Symlinking oldPath /run/resolvconf/resolv.conf with newPath /etc/resolv.conf
2022-06-24_08:58:15.56409 [File System] 2022/06/24 08:58:15 DEBUG - Lstat '/etc/resolv.conf'
2022-06-24_08:58:15.56426 [Cmd Runner] 2022/06/24 08:58:15 DEBUG - Running command 'resolvconf -u'
2022-06-24_08:58:15.58450 [Cmd Runner] 2022/06/24 08:58:15 DEBUG - Stdout:
2022-06-24_08:58:15.58457 [Cmd Runner] 2022/06/24 08:58:15 DEBUG - Stderr:
2022-06-24_08:58:15.58461 [Cmd Runner] 2022/06/24 08:58:15 DEBUG - Successful: true (0)
2022-06-24_08:58:15.58467 [File System] 2022/06/24 08:58:15 DEBUG - Reading file /etc/resolv.conf
2022-06-24_08:58:15.58471 [File System] 2022/06/24 08:58:15 DEBUG - Read content
2022-06-24_08:58:15.58472 ********************
2022-06-24_08:58:15.58473 nameserver 10.2.49.10
2022-06-24_08:58:15.58473 nameserver 10.2.49.20
2022-06-24_08:58:15.58474 nameserver 9.9.9.9
2022-06-24_08:58:15.58474 search dev.example.com
2022-06-24_08:58:15.58475
2022-06-24_08:58:15.58475 ********************
2022-06-24_08:58:15.58480 [main] 2022/06/24 08:58:15 ERROR - App setup Running bootstrap: Setting up networking: Validating dns configuration: None of the DNS servers that were specified in the manifest were found in /etc/resolv.conf.: <nil cause>
2022-06-24_08:58:15.58484 [main] 2022/06/24 08:58:15 ERROR - Agent exited with error: Running bootstrap: Setting up networking: Validating dns configuration: None of the DNS servers that were specified in the manifest were found in /etc/resolv.conf.: <nil cause>

```

guess that explains it.
