### ISSUE TITLE
Problems to generate the bosh dev release

### ISSUE THREAD

**Issue by andinod** [cloudfoundry/bosh-openstack-cpi-release#252]
Hi everbody,

currently I'm trying to generate a devel release for testing puporses of my changes in openstack cpi, and I found an issue where I don't have the answer. 

I'm getting the following error:

$ bosh create-release --force --tarball=/home/cloud-user/releases/bosh-openstack-cpi.tgz
-- Started downloading 'ruby-3.1.0-r0.81.0/9cf1a9582c595fd03eb9c73cd3c4b2d10de10c139f99ab0b9d1a71e5d2b91378' (sha1=sha256:85282a8dccc07b1395f26932e83b226a79814dd342eac3369f8330d9e70e7499)
-- Finished downloading 'ruby-3.1.0-r0.81.0/9cf1a9582c595fd03eb9c73cd3c4b2d10de10c139f99ab0b9d1a71e5d2b91378' (sha1=sha256:85282a8dccc07b1395f26932e83b226a79814dd342eac3369f8330d9e70e7499)

Building a release from directory '/home/cloud-user/bosh-openstack-cpi-release':
  - Expected source ('18be510ff294761f4e252dc6e4cb7d6211edf5bc54d8020416f17969c3df3eda') and staging ('3ef7c16eedbeb3d8b8298520a17e59df57ff46679d30f1eed7ea5e784525b8da') fingerprints to match
  - Expected source ('88c9609264d98d85571e026e62a8094af0c660041f18e5123aeaaf478528df90') and staging ('4a0912a5e22c4fb14d63ee9d5ce93faea85428706af66d3742a91c892ea761a9') fingerprints to match

Exit code 1

Can you please tell me what is the issue here? because it seems that file is downloaded but it differs in the fingerprint level. 
How can I fix that?

Thanks

David

**Comment by rkoster** [comment]
It seems to work on my machine:
```
❯ bosh create-release
-- Started downloading 'openstack_cpi/ac7eda22301ae26fde1fb55ea8b7b0fd65ca5725770ed5ec73849e40a119332a' (sha1=sha256:68d0c427e222d1b03310aeb0e480c390d30288a2ed17b05153f9163240a863af)
-- Started downloading 'bosh_openstack_cpi/4f3d5adf98165441449d37d3ef1a868532e8e227bf8ece42649d58ccc0f12b41' (sha1=sha256:ae9abb6d896156f4ca9e9fa951018649208250c880948c2f5ce28b961172afa5)
-- Finished downloading 'openstack_cpi/ac7eda22301ae26fde1fb55ea8b7b0fd65ca5725770ed5ec73849e40a119332a' (sha1=sha256:68d0c427e222d1b03310aeb0e480c390d30288a2ed17b05153f9163240a863af)
-- Finished downloading 'bosh_openstack_cpi/4f3d5adf98165441449d37d3ef1a868532e8e227bf8ece42649d58ccc0f12b41' (sha1=sha256:ae9abb6d896156f4ca9e9fa951018649208250c880948c2f5ce28b961172afa5)

Added dev release 'bosh-openstack-cpi/48+dev.1'

Name         bosh-openstack-cpi
Version      48+dev.1
Commit Hash  beda01f

Job                                                                             Digest                                                                   Packages
openstack_cpi/ac7eda22301ae26fde1fb55ea8b7b0fd65ca5725770ed5ec73849e40a119332a  sha256:68d0c427e222d1b03310aeb0e480c390d30288a2ed17b05153f9163240a863af  ruby-3.1.0-r0.81.0
                                                                                                                                                         bosh_openstack_cpi

1 jobs

Package                                                                              Digest                                                                   Dependencies
bosh_openstack_cpi/4f3d5adf98165441449d37d3ef1a868532e8e227bf8ece42649d58ccc0f12b41  sha256:ae9abb6d896156f4ca9e9fa951018649208250c880948c2f5ce28b961172afa5  ruby-3.1.0-r0.81.0
ruby-3.1.0-r0.81.0/9cf1a9582c595fd03eb9c73cd3c4b2d10de10c139f99ab0b9d1a71e5d2b91378  sha256:85282a8dccc07b1395f26932e83b226a79814dd342eac3369f8330d9e70e7499  -

2 packages

Succeeded
```
Could you try again after running `bosh reset-release`?

**Comment by andinod** [comment]
yes it works. Thanks a lot.
