### ISSUE TITLE
Unfortunately, an unexpected error occurred, and Bundler cannot continue.

### ISSUE THREAD

**Issue by andinod** [cloudfoundry/bosh-openstack-cpi-release#253]
Hello,

I've been trying to test my changes in live generating a dev release, but I all the time receive the same error. Just for you know I'm running behind a proxy.

**Installing CPI:
  Compiling job package dependencies for installation:
    Compiling job package dependencies:
      Compiling package:
        Running command: 'bash -x packaging', stdout: 'Bundler 2.3.22 is running, but your lockfile was generated with 2.3.7. Installing Bundler 2.3.7 and restarting using that version.
...
...
There was an error installing the locked bundler version (2.3.7), rerun with the `--verbose` flag for more details. Going on using bundler 2.3.22.
--- ERROR REPORT TEMPLATE -------------------------------------------------------

Errno::EADDRNOTAVAIL: Failed to open TCP connection to index.rubygems.org:443 (Cannot assign requested address - connect(2) for [2a04:4e42::483]:443)**

It shows a big report and then ends up with:

**Unfortunately, an unexpected error occurred, and Bundler cannot continue.**

I have tested and I have access to https://index.rubygems.org, so what could be the problem? and is there any way to fix it?

Thanks

David

**Comment by rkoster** [comment]
Have you tried running bundle package? It looks like bundler is trying to fetch a gem from the internet which it should not be doing during package compilation. All dependencies need to be provided by the bosh release.

**Comment by andinod** [comment]
On the other hand I can notice that he is referring to use bundler 2.3.22 and then it tries to use the 2.3.7 which is the one that it is supposed to use which at the end fails. 

To be honest that's a weird message, I've never seen something like that in a release...

On the other hand just to make sure it wasn't using any other cache I deleted the downloaded, cache and installation dirs from .bosh but I get the same result.

What am I missing ?

Thanks in advance 

David

**Comment by andinod** [comment]
Fixed in Version 50
