### ISSUE TITLE
GemNotFound

### ISSUE THREAD

**Issue by andinod** [cloudfoundry/bosh-openstack-cpi-release#254]
Hi,

I just tested in a clean installation the new release of the bosh openstack cpi, v49 and I received this message:

Started validating
  Downloading release 'bosh'... Finished (00:00:48)
  Validating release 'bosh'... Finished (00:00:00)
  Downloading release 'bpm'... Finished (00:01:11)
  Validating release 'bpm'... Finished (00:00:00)
  Downloading release 'bosh-openstack-cpi'... Finished (00:00:00)
  Validating release 'bosh-openstack-cpi'... Finished (00:00:00)
  Downloading release 'uaa'... Finished (00:02:13)
  Validating release 'uaa'... Finished (00:00:01)
  Downloading release 'os-conf'... Finished (00:00:00)
  Validating release 'os-conf'... Finished (00:00:00)
  Downloading release 'backup-and-restore-sdk'... Finished (00:03:12)
  Validating release 'backup-and-restore-sdk'... Finished (00:00:03)
  Downloading release 'credhub'... Finished (00:00:53)
  Validating release 'credhub'... Finished (00:00:00)
  Validating cpi release... Finished (00:00:00)
  Validating deployment manifest... Finished (00:00:00)
  Downloading stemcell... Finished (00:00:20)
  Validating stemcell... Finished (00:00:05)
Finished validating (00:08:54)

Started installing CPI
  Compiling package 'ruby-3.1/0aaa829929c32f6bcf3e51f82c37ba0535a8007870f86fe699cd194b077dbb96'... Finished (00:02:37)
  Compiling package 'bosh_openstack_cpi/161a44ae61e251e2b30a873e35007acf20901332fd51de31793933b7ea1cce6a'... Finished (00:00:45)
  Installing packages... Finished (00:00:00)
  Rendering job templates... Finished (00:00:00)
  Installing job 'openstack_cpi'... Finished (00:00:00)
Finished installing CPI (00:03:23)

Cleaning up rendered CPI jobs... Finished (00:00:00)

Error getting CPI info:
  Executing external CPI command: '/home/cloud-user/.bosh/installations/ff6c6aa7-9f5a-4057-50d1-76996e1d6cb8/jobs/openstack_cpi/bin/cpi':
    Running command: '/home/cloud-user/.bosh/installations/ff6c6aa7-9f5a-4057-50d1-76996e1d6cb8/jobs/openstack_cpi/bin/cpi', stdout: '', stderr: 'bundler: failed to load command: /home/cloud-user/.bosh/installations/ff6c6aa7-9f5a-4057-50d1-76996e1d6cb8/packages/bosh_openstack_cpi/bin/openstack_cpi (/home/cloud-user/.bosh/installations/ff6c6aa7-9f5a-4057-50d1-76996e1d6cb8/packages/bosh_openstack_cpi/bin/openstack_cpi)
/home/cloud-user/.bosh/installations/ff6c6aa7-9f5a-4057-50d1-76996e1d6cb8/packages/ruby-3.1/lib/ruby/site_ruby/3.1.0/bundler/definition.rb:518:in `materialize': Could not find ipaddress-0.8.3 in locally installed gems (**Bundler::GemNotFound**)

...
exit status 1

Exit code 1

before that I have cleaned up all cache from the .bosh directory and also any bundle dir to verify and get the same result..

Best

David

**Comment by lnguyen** [comment]
This is fixed in v50
